exec-once=waybar
exec-once=swaync
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=waytrogen --restore
exec-once=~/.config/mango/scripts/battery-warning.sh
exec-once=miru-daemon
